### ISSUE TITLE
TypeError: category.toLowerCase is not a function

### ISSUE THREAD

**Issue by alphabase** [alphabase/nl.nu.headlines#1]
A crash occurred for your app (version 1.0.2) at Feb 15, 2017 3:44 PM (UTC).

Homey software version: 1.1.9

Crash report: 
    TypeError: category.toLowerCase is not a function
    at getNewsItems (/app.js:50:22)
    at /app.js:40:4
    at process.<anonymous> (/homey-app/helpers/client.js:1:1269)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at internal/child_process.js:721:12
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

**Comment by alphabase** [comment]
Due to personal circumstances, I have not yet been able to reproduce this issue. If anyone happens to notice this issue and is able to provide me with a reproduction, I can fix this quickly 🙂

**Comment by alphabase** [comment]
The issue is caused by [apps.js:40](https://github.com/alphabase/nl.nu.headlines/blob/master/app.js#L40) when a category is requested through speech input, but none is given. The variable `result` is then `false`, while a string is required for the attribute `category` in function `getNewsItems()`.

Fix will be provided in the next update.

**Comment by alphabase** [comment]
Fixed in version 1.0.3, published to app store, awaiting approval.

**Comment by alphabase** [comment]
Version 1.0.3 published: https://apps.athom.com/app/nl.nu.headlines
